---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-mysql
type: Opaque
data:
stringData:
  conjur-map: |-
    username: vault01/LOBUser1/safe-ocp/dev-db/username
    password: vault01/LOBUser1/safe-ocp/dev-db/password
    database: vault01/LOBUser1/safe-ocp/dev-db/database
