---
# Deployment for Conjur Secrets Provider - push to file mode as sidecar
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
  namespace: $APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
      annotations:
        # Secrets Provider configuration
        conjur.org/container-mode: sidecar
        conjur.org/secrets-destination: file
        conjur.org/conjur-secrets-policy-path.test-app: secrets/$APP_NAME
        conjur.org/secret-file-template.test-app: |
          {{ secret "password" }}
        conjur.org/conjur-secrets.test-app: |
          - password
        conjur.org/secret-file-path.test-app: "./token"
        conjur.org/secret-file-format.test-app: "template"
        conjur.org/secrets-refresh-interval: 60s
        conjur.org/secrets-refresh-enabled: "true"
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        # Our demo application
        - name: demo-application
          image: centos:latest
          imagePullPolicy: Always
          command: ["sleep"]
          args: ["infinity"]
          # Path to the file with the secrets
          volumeMounts:
            - name: conjur-secrets
              mountPath: /opt/secrets/conjur
              readOnly: true
        # Sidecar container
        - image: registry.connect.redhat.com/cyberark/secrets-provider-for-k8s
          imagePullPolicy: IfNotPresent
          name: configurator
          env:
            - name: CONJUR_AUTHN_LOGIN
              value: $APP_HOST_ID
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - name: podinfo
              mountPath: /conjur/podinfo
            - name: conjur-secrets
              mountPath: /conjur/secrets
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: annotations
                fieldRef:
                  fieldPath: metadata.annotations
        - name: conjur-secrets
          emptyDir:
            medium: Memory