apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_SECRETS_K8S_INIT
  name: $APP_SECRETS_K8S_INIT
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $APP_SECRETS_K8S_INIT
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_SECRETS_K8S_INIT
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        - name: $APP_SECRETS_K8S_INIT
          image: $APP_IMAGE_NAME_BASIC
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx64m -XX:MaxMetaspaceSize=64m -Dspring.main.lazy-initialization=true -XX:TieredStopAtLevel=1 -XX:+UseSerialGC"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials-secrets-provider-for-k8s-init
                  key: url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials-secrets-provider-for-k8s-init
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials-secrets-provider-for-k8s-init
                  key: password
          ports:
            - containerPort: 8080
      initContainers:
        - image: $SECRETS_PROVIDER_IMAGE
          imagePullPolicy: Always
          name: $CONJUR_AUTH_K8S_CONTAINER_NAME
          volumeMounts:
            - name: conjur-status
              mountPath: /conjur/status
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
          env:
            - name: JWT_TOKEN_PATH
              value: /var/run/secrets/tokens/jwt
            - name: CONTAINER_MODE
              value: init
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_SECRETS
              value: db-credentials-secrets-provider-for-k8s-init
            - name: SECRETS_DESTINATION
              value: k8s_secrets
          envFrom:
            - configMapRef:
                name: conjur-connect
      volumes:
        - name: conjur-status
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_SECRETS_K8S_INIT
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32082
  selector:
    app: $APP_SECRETS_K8S_INIT