---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-sidecar-injector-secrets-provider-for-k8s-init
type: Opaque
data:
stringData:
  conjur-map: |-
    username: $APP_SECRET_USERNAME_PATH
    password: $APP_SECRET_PASSWORD_PATH
    url: $APP_SECRET_URL_PATH