---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secrets-provider-for-k8s-sidecar
type: Opaque
data:
stringData:
  conjur-map: |-
    username: vault01/LOBUser1/safe-ocp/dev-db/username
    password: vault01/LOBUser1/safe-ocp/dev-db/password
    url: vault01/LOBUser1/safe-ocp/dev-db/dsn