---
# Sidecar deployment manifest with empty centos application to consume the secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_MONGO_PUSH_FILE_SIDECAR
  name: $APP_MONGO_PUSH_FILE_SIDECAR
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $APP_MONGO_PUSH_FILE_SIDECAR
  replicas: 1
  template:
    metadata:
      annotations:
        conjur.org/container-mode: sidecar
        conjur.org/secrets-refresh-enabled: "true"
        conjur.org/secrets-refresh-interval: 10s
        conjur.org/secrets-destination: file
        conjur.org/conjur-secrets-policy-path.$APP_NAME: secrets/test-app
        conjur.org/conjur-secrets.$APP_NAME: |
          - mongo-uri
        conjur.org/secret-file-path.$APP_NAME: "./application.yml"
        conjur.org/secret-file-format.$APP_NAME: "template"
      labels:
        app: $APP_MONGO_PUSH_FILE_SIDECAR
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        # Sidecar container
        - image: $SECRETS_PROVIDER_IMAGE
          imagePullPolicy: IfNotPresent
          name: $CONJUR_AUTH_K8S_CONTAINER_NAME
          lifecycle:
            postStart:
              exec:
                command:
                  - /usr/local/bin/conjur-secrets-provided.sh
          env:
            - name: CONJUR_AUTHN_LOGIN
              value: $APP_HOST_ID
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - name: podinfo
              mountPath: /conjur/podinfo
            - name: conjur-secrets
              mountPath: /conjur/secrets
            - name: conjur-templates
              mountPath: /conjur/templates
            - mountPath: /conjur/status
              name: conjur-status
        # Demo MongoDB App - No change in source code
        - name: $APP_MONGO_PUSH_FILE_SIDECAR
          image: $APP_IMAGE_NAME_BASIC_MONGODB
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /opt/secrets/conjur/
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /conjur/status/conjur-secrets-unchanged.sh
            failureThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: conjur-secrets
              mountPath: /opt/secrets/conjur
            - name: conjur-templates
              mountPath: /conjur/templates
            - mountPath: /conjur/status
              name: conjur-status
          ports:
            - containerPort: 8080
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: annotations
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
            defaultMode: 420
        - name: conjur-secrets
          emptyDir:
            medium: Memory
        - name: conjur-templates
          configMap:
            name: spring-boot-templates
        - name: conjur-status
          emptyDir:
            medium: Memory
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_MONGO_PUSH_FILE_SIDECAR
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32190
  selector:
    app: $APP_MONGO_PUSH_FILE_SIDECAR
---