---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  password: NWIzZTVmNzVjYjNjZGM3MjVmZTQwMzE4
  url: bXlzcWw6Ly90ZXN0LWRiLW15c3FsLmJubC10ZXN0LWFwcC1uYW1lc3BhY2Uuc3ZjLmNsdXN0ZXIubG9jYWw6MzMwNi90ZXN0X2Ri
  username: dGVzdF9kYg==
