apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
  namespace: $APP_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_NAME
      annotations:
        # Secrets Provider configuration
        conjur.org/container-mode: sidecar
        conjur.org/secrets-destination: file
        conjur.org/conjur-secrets-policy-path.test-app: jwt-apps/secrets
        conjur.org/jwt-token-path: /var/run/secrets/tokens/jwt
        conjur.org/conjur-secrets.test-app: |
          - DB_USERNAME: username
          - DB_PASSWORD: password
          - DB_URL: url
        conjur.org/secret-file-path.test-app: "./credentials.properties"
        conjur.org/secret-file-format.test-app: "bash"
        conjur.org/secrets-refresh-interval: 60s
        conjur.org/secrets-refresh-enabled: "true"
    spec:
      serviceAccountName: $APP_SERVICE_ACCOUNT_NAME
      containers:
        - name: $APP_NAME
          image: $APP_IMAGE_NAME_BASIC
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "source /opt/secrets/conjur/credentials.properties && java -jar /app/target/conjur-k8s-demo-2.0.jar" ]
          # Path to the file with the secrets
          volumeMounts:
            - name: conjur-secrets
              mountPath: /opt/secrets/conjur
              readOnly: true
          ports:
            - containerPort: 8080
        - image: $SECRETS_PROVIDER_IMAGE
          imagePullPolicy: IfNotPresent
          name: $CYBERARK_CONJUR_AUTH_K8S_CONTAINER_NAME
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: conjur-connect
          volumeMounts:
            - name: conjur-status
              mountPath: /conjur/status
            - name: podinfo
              mountPath: /conjur/podinfo
            - name: conjur-secrets
              mountPath: /conjur/secrets
            - name: jwt-token
              mountPath: /var/run/secrets/tokens
      volumes:
        - name: conjur-status
          emptyDir:
            medium: Memory
        - name: podinfo
          downwardAPI:
            items:
              - path: annotations
                fieldRef:
                  fieldPath: metadata.annotations
        - name: conjur-secrets
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: conjur
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
  namespace: $APP_NAMESPACE
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32082
  selector:
    app: $APP_NAME