apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: controller-manager
  name: conjur-follower-operator-controller-manager
  namespace: $CONJUR_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjur-follower-operator-conjurfollower-editor-role
rules:
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurfollowers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurfollowers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjur-follower-operator-conjurfollower-viewer-role
rules:
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurfollowers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurfollowers/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: conjur-follower-operator-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - pods/exec
  verbs:
  - create
  - get
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurfollowers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurfollowers
  - conjurfollowers/finalizers
  verbs:
  - '*'
- apiGroups:
  - conjur.cyberark.com
  resources:
  - conjurfollowers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - watch
  - delete
- apiGroups:
  - extensions
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: conjur-follower-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-follower-operator-manager-role
subjects:
- kind: ServiceAccount
  name: conjur-follower-operator-controller-manager
  namespace: $CONJUR_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conjur-follower-operator-controller-manager
  namespace: $CONJUR_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      name: controller-manager
  template:
    metadata:
      labels:
        name: controller-manager
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: conjur-follower-operator
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: $FOLLOWER_OPERATOR_IMAGE
        imagePullPolicy: Always
        name: conjur-follower-operator
      serviceAccountName: conjur-follower-operator-controller-manager
